[functions]
  directory = "src/endpoints"

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200
